### ISSUE TITLE
compile error with gcc14

### ISSUE THREAD

**Issue by wangmingyu84** [kkaempf/cmpi-bindings#16]
when gcc updated to gcc14, the compile failed:

src/target_python.c:168:21: error: passing argument 1 of 'Py_SetProgramName' from incompatible pointer type [-Wincompatible-pointer-types]
|   168 |   Py_SetProgramName("cmpi_swig");
|       |                     ^~~~~~~~~~~
|       |                     |
|       |                     char *

**Comment by kkaempf** [comment]
fixed by #17
